# homepage
GET http://localhost:3000/api

###
# get all blogs
GET http://localhost:3000/api/blogs

###
# post a blog
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "content": "test"
}

###
# get a specific blog
GET http://localhost:3000/api/blogs/6682453c2acc31cee6e28913


###
# update a specific blog
PUT http://localhost:3000/api/blogs/6682453c2acc31cee6e28913
Content-Type: application/json

{
    "content": "update test"
}

###
# delete a blog
DELETE http://localhost:3000/api/blogs/66823e177125a0eab1df7802

